source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      order: 100


title: Java Annotation Processor Toolkit
repository: "holisticon/annotation-processor-toolkit"
email: your-email@example.com
description: >
  Eases development and testing of annotation processors
baseurl: "/annotation-processor-toolkit" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  holisticon

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

theme: jekyll-theme-architect
gems:
  - jekyll-feed


tz: Europe/Berlin

